import React from 'react';
import { 
  MessageCircle, 
  Users, 
  User, 
  Settings, 
  Plus, 
  QrCode, 
  Scan, 
  Send, 
  ArrowLeft,
  Sparkles,
  Camera,
  X,
  Search,
  MoreVertical,
  Bot,
  Phone,
  Video,
  Check,
  CheckCheck,
  FileText,
  Globe,
  Briefcase,
  Moon,
  LogOut,
  ChevronDown,
  CircleFadingPlus,
  Aperture
} from 'lucide-react';

export const Icons = {
  Message: MessageCircle,
  Users: Users,
  User: User,
  Settings: Settings,
  Plus: Plus,
  QrCode: QrCode,
  Scan: Scan,
  Send: Send,
  Back: ArrowLeft,
  Sparkles: Sparkles,
  Camera: Camera,
  Close: X,
  Search: Search,
  More: MoreVertical,
  Bot: Bot,
  Phone: Phone,
  Video: Video,
  Check: Check,
  CheckCheck: CheckCheck,
  File: FileText,
  Globe: Globe,
  Briefcase: Briefcase,
  Moon: Moon,
  LogOut: LogOut,
  ChevronDown: ChevronDown,
  Story: CircleFadingPlus,
  Aperture: Aperture
};